### ISSUE TITLE
Browser icons/logos not showing up

### ISSUE THREAD

**Issue by teleject** [norcross/caniuse-shortcode#1]
I'm looking into this issue now--appears that the icon font(?) isn't showing up:

<img width="680" alt="screen shot 2016-03-15 at 7 59 20 pm" src="https://cloud.githubusercontent.com/assets/41737/13798901/80960146-eae8-11e5-9b1e-f23c007f5c3a.png">

**Comment by teleject** [comment]
Looks like the CSS and font files need to be added manually?

**Comment by norcross** [comment]
The CSS and font files are there, but it looks like the CSS isn't getting picked up properly. pushing an update shortly.

**Comment by teleject** [comment]
Totally did the trick! Thanks!
