### ISSUE TITLE
Wrong data is being loaded (?)

### ISSUE THREAD

**Issue by crnacura** [norcross/caniuse-shortcode#2]
Hello,
it seems like the wrong data (the one of "stream") gets loaded for some CSS properties. For example "grid-layout": https://tympanus.net/codrops/css_reference/grid/#section_browser-support
Any ideas why this might be happening?
Thank you

**Comment by norcross** [comment]
I can check the data source to see if it's up to date

**Comment by crnacura** [comment]
@norcross Just figured out that the data is actually correct! It's just the link in "Stats from caniuse.com" that is always pointing to the stream entry. Thanks a lot

**Comment by norcross** [comment]
aahhhhh. thanks for following up.

**Comment by crnacura** [comment]
The problem seems to be in line 166 of display.php... The link is always "http://caniuse.com/#feat=stream" while it should be the one of the respective Can I Use entry.

**Comment by norcross** [comment]
oh, ok. lemme see about updating that
