### ISSUE TITLE
Error with loading files

### ISSUE THREAD

**Issue by crnacura** [norcross/caniuse-shortcode#3]
When opening our RSS feed at https://tympanus.net/codrops/feed/ it shows the following error:

Warning: require_once(lib/front.php): failed to open stream: No such file or directory in /home/tympanus/public_html/codrops/wp-content/plugins/caniuse-shortcode/caniuse-shortcode.php on line 103

Fatal error: require_once(): Failed opening required 'lib/front.php' (include_path='.:/usr/lib/php:/usr/local/lib/php') in /home/tympanus/public_html/codrops/wp-content/plugins/caniuse-shortcode/caniuse-shortcode.php on line 103

It seems like the file path is wrong since the latest update. 

(The error is not live anymore since I had to disable the plugin...)

Could you have a look?
Thanks

**Comment by norcross** [comment]
I hadn't considered the RSS feed aspect of it. I'll see what's up.

**Comment by norcross** [comment]
can you confirm the root file matches up with what's in the repo? Because you're showing an error on line 103, but the entire file only has 98 lines. Also, try changing the `require_once` calls to include the directory constant:

`require_once( 'lib/front.php' );` 
becomes 
`require_once( CIU_SHORTCODE_DIR . 'lib/front.php' );`

**Comment by crnacura** [comment]
Thank you, yes I can confirm that they match. And the file has 98 lines. It was the same thing I was wondering about when I saw the error... I'll try changing the paths and let you know how it goes.

**Comment by crnacura** [comment]
Ok, that worked, no more errors showing up in the feed.

**Comment by norcross** [comment]
awesome. I'll update the repo to include that fix
